"""add_totp_fields

Revision ID: 3a9b0d36a7c7
Revises: 82ae5bfae140
Create Date: 2026-04-07 19:13:09.341324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3a9b0d36a7c7'
down_revision: Union[str, Sequence[str], None] = '82ae5bfae140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('totp_secret', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    op.add_column('user', sa.Column('is_totp_enabled', sa.Boolean(), nullable=False))
    op.alter_column('user', 'id_no',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id_no',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('user', 'is_totp_enabled')
    op.drop_column('user', 'totp_secret')
    # ### end Alembic commands ###
