"""increase totp_secret column length

Revision ID: 4a103841fa58
Revises: 3a9b0d36a7c7
Create Date: 2026-04-07 21:52:30.753501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4a103841fa58"
down_revision: Union[str, Sequence[str], None] = "3a9b0d36a7c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "totp_secret",
        existing_type=sa.VARCHAR(length=32),
        type_=sqlmodel.sql.sqltypes.AutoString(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "totp_secret",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
        type_=sa.VARCHAR(length=32),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
